# Generated by Django 5.2.7 on 2025-11-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_match_status_scoreprediction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoreprediction',
            unique_together=set(),
        ),
    ]
