# Generated by Django 5.2.6 on 2025-10-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, null=True)),
                ('nama_klub', models.CharField(max_length=100, unique=True)),
                ('jumlah_win', models.PositiveIntegerField(default=0)),
                ('jumlah_lose', models.PositiveIntegerField(default=0)),
                ('jumlah_draw', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
    ]
