# Generated by Django 5.2.5 on 2025-10-26 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
        migrations.AlterField(
            model_name='club',
            name='jumlah_draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='jumlah_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='jumlah_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='nama_klub',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ClubComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
