# Generated by Django 5.2.6 on 2025-10-24 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('profile_picture_url', models.ImageField(blank=True, null=True, upload_to='player_thumbnails/')),
                ('citizenship', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=0)),
                ('curr_goals', models.PositiveIntegerField(default=0)),
                ('curr_assists', models.PositiveIntegerField(default=0)),
                ('match_played', models.PositiveIntegerField(default=0)),
                ('curr_cleansheet', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
