# Generated by Django 5.2.7 on 2025-10-22 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=100)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('citizenship', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('curr_goals', models.PositiveIntegerField()),
            ],
        ),
    ]
