# Generated by Django 5.2.7 on 2025-10-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='player_thumbnails/'),
        ),
    ]
