# Generated by Django 5.2.6 on 2025-10-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile_picture_url',
        ),
    ]
