# Generated by Django 5.2.6 on 2025-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='player_thumbnails/'),
        ),
    ]
